# Generated by Django 4.1.2 on 2022-11-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('monolit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
