# Generated by Django 4.1.2 on 2022-11-01 18:45

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('monolit', '0002_news_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_color',
            field=colorfield.fields.ColorField(default=16777215, image_field=None, max_length=18, samples=None),
        ),
    ]
